### ISSUE TITLE
“err” missing in custom callback arguments

### ISSUE THREAD

**Issue by oliverwehn** [rkusa/koa-passport#69]
When `authenticate` is called with a custom callback to override default behavior, the callback expects the four arguments  `err`, `user`, `info` and `status`. 

In [v2.x/lib/framework/koa.js#L95](https://github.com/rkusa/koa-passport/blob/v2.x/lib/framework/koa.js#L95) the `err` argument is missing where the original callback is called.
```javascript
    const _callback = callback
    callback = function(err, user, info, status) {
      if (err) {
        callback.reject(err)
      } else {
        Promise.resolve(_callback(user, info, status)) // should be (err, user, info, status)
               .then(() => callback.resolve(false))
               .catch(err => callback.reject(err))
      }
    }
```
Just to keep the usage of custom callbacks consistent with how it is described in the official [Passport docs](http://passportjs.org/docs/authenticate#custom-callback).

And just a question on the side: Why isn’t it `callback.resolve(…` instead of `Promise.resolve`? `reject` and `resolve` are both assigned on [line 131–134](https://github.com/rkusa/koa-passport/blob/v2.x/lib/framework/koa.js#L131-L134).

**Comment by rkusa** [comment]
Hi, thanks for the feedback, I really appreciate it! But I cannot give you a full answer, yet. I've to find some more time to thing about it.
Because, I agree that we should be consistent with Passport's docs, but in the current code, in case of an `err`, `_callback` is never called. Which is maybe also unintended behavior... I'll try to further elaborate this soon ...

**Comment by rkusa** [comment]
I've added the `err` argument. The change is contained in `3.0.0-rc.1`.
Thanks again for the feedback!
