### ISSUE TITLE
Authorization and passReqToCallback

### ISSUE THREAD

**Issue by felixsanz** [rkusa/koa-passport#84]
This is related with #42 and many other ones issues.

[http://passportjs.org/docs/authorize](http://passportjs.org/docs/authorize) 

The thing is, i want to "connect social login to an existing account", i first wanted to use the `authorize` method, but having troubles with that, i took another read to the docs and found the `passReqToCallback` thing, which seems to be a better solution. The problem is that i think it doesn't work as it should.

> To avoid this, set the strategy's passReqToCallback option to true. With this option enabled, req will be passed as the first argument to the verify callback.

```javascript
passport.use(new TwitterStrategy({
    consumerKey: TWITTER_CONSUMER_KEY,
    consumerSecret: TWITTER_CONSUMER_SECRET,
    callbackURL: "http://www.example.com/auth/twitter/callback",
    passReqToCallback: true
  },
  function(req, token, tokenSecret, profile, done) {
    // HERE
  }
})
```

In the comment position, `req` it's a reference to `ctx.req` but it should be a reference to `ctx`. Why? Because `ctx.state.user` must be usable there (`req.user` in express)

Maybe i'm wrong but i'm just receiving `method`, `url` and `header` properties from the `req` object, and the point is to receive the `user` object inside `ctx.state`.

Anyway, since koa have the `ctx.state` object for this kind of things, i'd say pass `ctx.state` to the callback instead of the full `ctx` object.

**Comment by rkusa** [comment]
Thanks for the feedback. Providing something else then `req` in a strategy callback is not easily done for koa-passport, because it only wraps existing `passport` functions. However, if there is a real use case I will elaborate possible ways. Therefor, I have a question to understand your use case. Why do you want to have access to the user object in the strategy, because usually the user object is not existing yet, when the strategy callback is called. The strategy callback usually returns a user object which is afterwards (but not before) available from `ctx.state.user`.

**Comment by felixsanz** [comment]
@rkusa The use case is to connect social logins with an existing account (instead of creating a new account for every social login). This is super important i think, not an edge use case.

----

http://passportjs.org/docs/authorize

> An application may need to incorporate information from multiple third-party services. In this case, the application will request the user to "connect", for example, both their Facebook and Twitter accounts.

> When this occurs, a user will already be authenticated with the application, and any subsequent third-party accounts merely need to be authorized and associated with the user. Because authentication and authorization in this situation are similar, Passport provides a means to accommodate both.

---

> **Association in Verify Callback**

> One downside to the approach described above is that it requires two instances of the same strategy and supporting routes.

> To avoid this, set the strategy's passReqToCallback option to true. With this option enabled, req will be passed as the first argument to the verify callback.

**Comment by rkusa** [comment]
The user is for compatibility reasons with passport strategies also available at `req.user` (at least as a getter). Alternatively, you could also use [`domain`](https://nodejs.org/dist/latest-v7.x/docs/api/domain.html). Does this help?

**Comment by felixsanz** [comment]
Domains are deprecated...

Did you take a look at my message? Because i don't think your response relates at all with it. Or i didn't understand you at all.

> The user is for compatibility reasons with passport strategies

What do you mean? And how does it relates to having the user object available at the callback time?

Thanks

**Comment by rkusa** [comment]
Yes the  `domain` module is deprecated, but according to the docs, there will be a replacement in place before it is actually removed.

I did read your message, but did not invest to much time into an answer (sorry for that, but I am quite busy these days; anyway, it is still possible that I got you wrong). If I got you right, you need access to the currently logged in user during the execution of a callback of a passport strategy. The following code does work for `koa-passport`:

```js
const FacebookStrategy = require('passport-facebook').Strategy
passport.use(new FacebookStrategy({
    clientID: '...',
    clientSecret: '...',
    callbackURL: '...',
    passReqToCallback: true
  },
  function(req, token, tokenSecret, profile, done) {
    console.log(req, req.user)
```

The reason is that in `koa-passport` `req.user` still exists (it is a getter, which returns ctx.state.user). Since this works as expected, your use case should be fulfilled, shouldn't it? (in my first comment to this issue I forget that `req.user` still exists 😉)

**Comment by felixsanz** [comment]
That clear the issue. I think i was messing with req.state.user and not req.user :/

Now i see it as a stupid question, sorry ;P

Thanks

**Comment by rkusa** [comment]
You are welcome! :-)

**Comment by margox** [comment]
I have the same issue, and there is no property "user" in object "req":
```
{ method: 'GET',
  url: '/api/public/auth/github/callback?code=xxxxxx',
  header: {
     host: 'coffee-cms.com',
     connection: 'keep-alive',
     pragma: 'no-cache',
     'cache-control': 'no-cache',
     'upgrade-insecure-requests': '1',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
     'accept-encoding': 'gzip, deflate, sdch',
     'accept-language': 'en,zh-CN;q=0.8,zh;q=0.6,zh-TW;q=0.4,es;q=0.2,sw;q=0.2',
     cookie: 'coffee-secret=LUP5OwEhaxF0j0qOYw7x9i7P1jyoUMxt; coffee-secret.sig=X1_t5WLapNZUn89j0oM1qotEz3U' 
   }
 }
```
I can get the encoded cookie from "req", if I can parse it, maybe there is a way to get the information of the current logined user, is there any function or npm module that can parse the cookie?
